#ifndef KYSDKSOUNDEFFECTS_GLOBAL_H
#define KYSDKSOUNDEFFECTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KYSDKSOUNDEFFECTS_LIBRARY)
#  define KYSDKSOUNDEFFECTS_EXPORT Q_DECL_EXPORT
#else
#  define KYSDKSOUNDEFFECTS_EXPORT Q_DECL_IMPORT
#endif

#endif // KYSDKSOUNDEFFECTS_GLOBAL_H
